[package]
name = "tail-id"
description = "Resolve partial UUIDs against collections using suffix matching"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/mbr/tail-id"

[features]
default = []
serde = ["dep:serde"]
schemars = ["dep:schemars"]

[dependencies]
schemars = { version = "0.8", optional = true }
serde = { version = "1", optional = true }
thiserror = "2"
uuid = "1"

[dev-dependencies]
uuid = { version = "1", features = ["v4", "v7"] }
